//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheShop.Web.Resources {
    using System;

    /// <summary>
    ///   A strongly-typed resource class for looking up localized strings, etc.
    ///   Generated from Strings.resx. Access via the static properties below.
    ///   Uses the current thread culture for look-up, just like IStringLocalizer.
    ///
    ///   Usage (Pattern 1 — preferred for compile-time-known keys):
    ///       @Strings.AddToCart
    ///       @string.Format(Strings.Product_StockWarning, count)
    ///
    ///   Usage (Pattern 2 — for runtime-resolved keys returned from Application layer):
    ///       @Localizer[result.Error]   ← inject IStringLocalizer&lt;Strings&gt; Localizer
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheShop.Web.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        ///   Leave null to follow the current thread culture automatically.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        // ============================================================
        // Common / Shared
        // ============================================================

        /// <summary>The Vape Shop Sarnia</summary>
        public static string AppName {
            get { return ResourceManager.GetString("AppName", resourceCulture)!; }
        }

        /// <summary>Cancel / Annuler</summary>
        public static string Cancel {
            get { return ResourceManager.GetString("Cancel", resourceCulture)!; }
        }

        /// <summary>Save / Enregistrer</summary>
        public static string Save {
            get { return ResourceManager.GetString("Save", resourceCulture)!; }
        }

        /// <summary>Continue / Continuer</summary>
        public static string Continue {
            get { return ResourceManager.GetString("Continue", resourceCulture)!; }
        }

        /// <summary>Back / Retour</summary>
        public static string Back {
            get { return ResourceManager.GetString("Back", resourceCulture)!; }
        }

        /// <summary>Loading… / Chargement…</summary>
        public static string Loading {
            get { return ResourceManager.GetString("Loading", resourceCulture)!; }
        }

        // ============================================================
        // Navigation
        // ============================================================

        /// <summary>Home / Accueil</summary>
        public static string Nav_Home {
            get { return ResourceManager.GetString("Nav_Home", resourceCulture)!; }
        }

        /// <summary>Products / Produits</summary>
        public static string Nav_Products {
            get { return ResourceManager.GetString("Nav_Products", resourceCulture)!; }
        }

        /// <summary>Cart / Panier</summary>
        public static string Nav_Cart {
            get { return ResourceManager.GetString("Nav_Cart", resourceCulture)!; }
        }

        /// <summary>Account / Compte</summary>
        public static string Nav_Account {
            get { return ResourceManager.GetString("Nav_Account", resourceCulture)!; }
        }

        /// <summary>Admin Panel / Panneau d'administration</summary>
        public static string Nav_AdminPanel {
            get { return ResourceManager.GetString("Nav_AdminPanel", resourceCulture)!; }
        }

        // ============================================================
        // Home page
        // ============================================================

        /// <summary>Home — The Vape Shop Sarnia / Accueil — …</summary>
        public static string Home_PageTitle {
            get { return ResourceManager.GetString("Home_PageTitle", resourceCulture)!; }
        }

        /// <summary>Welcome to The Vape Shop Sarnia / Bienvenue à …</summary>
        public static string Home_Welcome {
            get { return ResourceManager.GetString("Home_Welcome", resourceCulture)!; }
        }

        // ============================================================
        // Not Found page
        // ============================================================

        /// <summary>Page Not Found — The Vape Shop Sarnia</summary>
        public static string NotFound_PageTitle {
            get { return ResourceManager.GetString("NotFound_PageTitle", resourceCulture)!; }
        }

        /// <summary>404 — Page Not Found / 404 — Page introuvable</summary>
        public static string NotFound_Heading {
            get { return ResourceManager.GetString("NotFound_Heading", resourceCulture)!; }
        }

        /// <summary>Sorry, the page you are looking for does not exist.</summary>
        public static string NotFound_Message {
            get { return ResourceManager.GetString("NotFound_Message", resourceCulture)!; }
        }

        /// <summary>Go to Home / Aller à l'accueil</summary>
        public static string NotFound_GoHome {
            get { return ResourceManager.GetString("NotFound_GoHome", resourceCulture)!; }
        }

        // ============================================================
        // Products
        // ============================================================

        /// <summary>Products — The Vape Shop Sarnia / Produits — …</summary>
        public static string Products_PageTitle {
            get { return ResourceManager.GetString("Products_PageTitle", resourceCulture)!; }
        }

        /// <summary>Product Details — The Vape Shop Sarnia</summary>
        public static string ProductDetail_PageTitle {
            get { return ResourceManager.GetString("ProductDetail_PageTitle", resourceCulture)!; }
        }

        /// <summary>Add to Cart / Ajouter au panier</summary>
        public static string AddToCart {
            get { return ResourceManager.GetString("AddToCart", resourceCulture)!; }
        }

        /// <summary>Item added to your cart. / Article ajouté à votre panier.</summary>
        public static string AddedToCart {
            get { return ResourceManager.GetString("AddedToCart", resourceCulture)!; }
        }

        /// <summary>Could not add item to cart. Please try again.</summary>
        public static string AddToCart_Failed {
            get { return ResourceManager.GetString("AddToCart_Failed", resourceCulture)!; }
        }

        /// <summary>Photo of {0} / Photo de {0}  — use string.Format()</summary>
        public static string Product_ImageAlt {
            get { return ResourceManager.GetString("Product_ImageAlt", resourceCulture)!; }
        }

        /// <summary>Only {0} left in stock / Seulement {0} en stock  — use string.Format()</summary>
        public static string Product_StockWarning {
            get { return ResourceManager.GetString("Product_StockWarning", resourceCulture)!; }
        }

        /// <summary>This product could not be found. / Ce produit est introuvable.</summary>
        public static string ProductNotFound {
            get { return ResourceManager.GetString("ProductNotFound", resourceCulture)!; }
        }

        /// <summary>No products found. / Aucun produit trouvé.</summary>
        public static string Empty_NoResults {
            get { return ResourceManager.GetString("Empty_NoResults", resourceCulture)!; }
        }

        // ============================================================
        // Cart
        // ============================================================

        /// <summary>Cart — The Vape Shop Sarnia / Panier — …</summary>
        public static string Cart_PageTitle {
            get { return ResourceManager.GetString("Cart_PageTitle", resourceCulture)!; }
        }

        /// <summary>Your cart is empty. / Votre panier est vide.</summary>
        public static string Empty_Cart {
            get { return ResourceManager.GetString("Empty_Cart", resourceCulture)!; }
        }

        // ============================================================
        // Checkout
        // ============================================================

        /// <summary>Checkout — The Vape Shop Sarnia / Paiement — …</summary>
        public static string Checkout_PageTitle {
            get { return ResourceManager.GetString("Checkout_PageTitle", resourceCulture)!; }
        }

        /// <summary>Place Order / Passer la commande</summary>
        public static string Checkout_PlaceOrder {
            get { return ResourceManager.GetString("Checkout_PlaceOrder", resourceCulture)!; }
        }

        /// <summary>Your order has been placed successfully!</summary>
        public static string OrderPlaced {
            get { return ResourceManager.GetString("OrderPlaced", resourceCulture)!; }
        }

        // ============================================================
        // Account / Auth
        // ============================================================

        /// <summary>My Account — The Vape Shop Sarnia / Mon compte — …</summary>
        public static string Account_PageTitle {
            get { return ResourceManager.GetString("Account_PageTitle", resourceCulture)!; }
        }

        /// <summary>Sign In — The Vape Shop Sarnia / Se connecter — …</summary>
        public static string Login_PageTitle {
            get { return ResourceManager.GetString("Login_PageTitle", resourceCulture)!; }
        }

        /// <summary>Sign In / Se connecter</summary>
        public static string Login {
            get { return ResourceManager.GetString("Login", resourceCulture)!; }
        }

        /// <summary>Sign Out / Se déconnecter</summary>
        public static string Logout {
            get { return ResourceManager.GetString("Logout", resourceCulture)!; }
        }

        /// <summary>Are you sure you want to sign out?</summary>
        public static string Confirm_Logout {
            get { return ResourceManager.GetString("Confirm_Logout", resourceCulture)!; }
        }

        /// <summary>Email address / Adresse courriel</summary>
        public static string Email_Label {
            get { return ResourceManager.GetString("Email_Label", resourceCulture)!; }
        }

        /// <summary>you@example.com / vous@exemple.com</summary>
        public static string Email_Placeholder {
            get { return ResourceManager.GetString("Email_Placeholder", resourceCulture)!; }
        }

        /// <summary>Email address is required. / L'adresse courriel est requise.</summary>
        public static string Email_Required {
            get { return ResourceManager.GetString("Email_Required", resourceCulture)!; }
        }

        /// <summary>Password / Mot de passe</summary>
        public static string Password_Label {
            get { return ResourceManager.GetString("Password_Label", resourceCulture)!; }
        }

        /// <summary>Minimum 8 characters. / Minimum 8 caractères.</summary>
        public static string Password_Hint {
            get { return ResourceManager.GetString("Password_Hint", resourceCulture)!; }
        }

        /// <summary>Password must be at least 8 characters.</summary>
        public static string Password_TooShort {
            get { return ResourceManager.GetString("Password_TooShort", resourceCulture)!; }
        }

        // ============================================================
        // Admin
        // ============================================================

        /// <summary>Dashboard — Admin — The Vape Shop Sarnia</summary>
        public static string AdminDashboard_PageTitle {
            get { return ResourceManager.GetString("AdminDashboard_PageTitle", resourceCulture)!; }
        }

        /// <summary>Products — Admin — The Vape Shop Sarnia</summary>
        public static string AdminProducts_PageTitle {
            get { return ResourceManager.GetString("AdminProducts_PageTitle", resourceCulture)!; }
        }

        /// <summary>Orders — Admin — The Vape Shop Sarnia</summary>
        public static string AdminOrders_PageTitle {
            get { return ResourceManager.GetString("AdminOrders_PageTitle", resourceCulture)!; }
        }

        /// <summary>Customers — Admin — The Vape Shop Sarnia</summary>
        public static string AdminCustomers_PageTitle {
            get { return ResourceManager.GetString("AdminCustomers_PageTitle", resourceCulture)!; }
        }
    }
}
