//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheShop.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheShop.Web.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back!.
        /// </summary>
        public static string Account_Greeting {
            get {
                return ResourceManager.GetString("Account_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account — The Vape Shop Sarnia.
        /// </summary>
        public static string Account_PageTitle {
            get {
                return ResourceManager.GetString("Account_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed in as {0}.
        /// </summary>
        public static string Account_SignedInAs {
            get {
                return ResourceManager.GetString("Account_SignedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, {0}!.
        /// </summary>
        public static string Account_Welcome {
            get {
                return ResourceManager.GetString("Account_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item added to your cart..
        /// </summary>
        public static string AddedToCart {
            get {
                return ResourceManager.GetString("AddedToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add item to cart. Please try again..
        /// </summary>
        public static string AddToCart_Failed {
            get {
                return ResourceManager.GetString("AddToCart_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers — Admin — The Vape Shop Sarnia.
        /// </summary>
        public static string AdminCustomers_PageTitle {
            get {
                return ResourceManager.GetString("AdminCustomers_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard — Admin — The Vape Shop Sarnia.
        /// </summary>
        public static string AdminDashboard_PageTitle {
            get {
                return ResourceManager.GetString("AdminDashboard_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders — Admin — The Vape Shop Sarnia.
        /// </summary>
        public static string AdminOrders_PageTitle {
            get {
                return ResourceManager.GetString("AdminOrders_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products — Admin — The Vape Shop Sarnia.
        /// </summary>
        public static string AdminProducts_PageTitle {
            get {
                return ResourceManager.GetString("AdminProducts_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Vaping, Curated for You..
        /// </summary>
        public static string App_Tagline {
            get {
                return ResourceManager.GetString("App_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Vape Shop Sarnia.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with this email already exists..
        /// </summary>
        public static string Auth_AccountAlreadyExists {
            get {
                return ResourceManager.GetString("Auth_AccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account found for this email..
        /// </summary>
        public static string Auth_AccountNotFound {
            get {
                return ResourceManager.GetString("Auth_AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Auth_Change {
            get {
                return ResourceManager.GetString("Auth_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect code. Please try again..
        /// </summary>
        public static string Auth_Code_Incorrect {
            get {
                return ResourceManager.GetString("Auth_Code_Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code is invalid or has expired..
        /// </summary>
        public static string Auth_Code_InvalidOrExpired {
            get {
                return ResourceManager.GetString("Auth_Code_InvalidOrExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent a 6-digit code to your email..
        /// </summary>
        public static string Auth_CodeSent {
            get {
                return ResourceManager.GetString("Auth_CodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Auth_Create_Submit {
            get {
                return ResourceManager.GetString("Auth_Create_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date of birth..
        /// </summary>
        public static string Auth_Dob_InPast {
            get {
                return ResourceManager.GetString("Auth_Dob_InPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required..
        /// </summary>
        public static string Auth_FirstName_Required {
            get {
                return ResourceManager.GetString("Auth_FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required..
        /// </summary>
        public static string Auth_LastName_Required {
            get {
                return ResourceManager.GetString("Auth_LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Auth_Login_Submit {
            get {
                return ResourceManager.GetString("Auth_Login_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t reach the server. Please check your connection and try again..
        /// </summary>
        public static string Auth_Network {
            get {
                return ResourceManager.GetString("Auth_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait before requesting a new code..
        /// </summary>
        public static string Auth_ResendTooSoon {
            get {
                return ResourceManager.GetString("Auth_ResendTooSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send code.
        /// </summary>
        public static string Auth_SendCode {
            get {
                return ResourceManager.GetString("Auth_SendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in again to continue..
        /// </summary>
        public static string Auth_SessionExpired {
            get {
                return ResourceManager.GetString("Auth_SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed in..
        /// </summary>
        public static string Auth_SignedIn {
            get {
                return ResourceManager.GetString("Auth_SignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been signed out..
        /// </summary>
        public static string Auth_SignedOut {
            get {
                return ResourceManager.GetString("Auth_SignedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many incorrect attempts. Please start again..
        /// </summary>
        public static string Auth_TooManyAttempts {
            get {
                return ResourceManager.GetString("Auth_TooManyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be at least 19 years old to create an account..
        /// </summary>
        public static string Auth_Underage {
            get {
                return ResourceManager.GetString("Auth_Underage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again..
        /// </summary>
        public static string Auth_Unexpected {
            get {
                return ResourceManager.GetString("Auth_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are here:.
        /// </summary>
        public static string Breadcrumb_AriaLabel {
            get {
                return ResourceManager.GetString("Breadcrumb_AriaLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart — The Vape Shop Sarnia.
        /// </summary>
        public static string Cart_PageTitle {
            get {
                return ResourceManager.GetString("Cart_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout — The Vape Shop Sarnia.
        /// </summary>
        public static string Checkout_PageTitle {
            get {
                return ResourceManager.GetString("Checkout_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order.
        /// </summary>
        public static string Checkout_PlaceOrder {
            get {
                return ResourceManager.GetString("Checkout_PlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to sign out?.
        /// </summary>
        public static string Confirm_Logout {
            get {
                return ResourceManager.GetString("Confirm_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be at least 19 years old..
        /// </summary>
        public static string DateOfBirth_Hint {
            get {
                return ResourceManager.GetString("DateOfBirth_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string DateOfBirth_Label {
            get {
                return ResourceManager.GetString("DateOfBirth_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string Email_Invalid {
            get {
                return ResourceManager.GetString("Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Email_Label {
            get {
                return ResourceManager.GetString("Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you@example.com.
        /// </summary>
        public static string Email_Placeholder {
            get {
                return ResourceManager.GetString("Email_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required..
        /// </summary>
        public static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cart is empty..
        /// </summary>
        public static string Empty_Cart {
            get {
                return ResourceManager.GetString("Empty_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products found..
        /// </summary>
        public static string Empty_NoResults {
            get {
                return ResourceManager.GetString("Empty_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName_Label {
            get {
                return ResourceManager.GetString("FirstName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home — The Vape Shop Sarnia.
        /// </summary>
        public static string Home_PageTitle {
            get {
                return ResourceManager.GetString("Home_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to The Vape Shop Sarnia.
        /// </summary>
        public static string Home_Welcome {
            get {
                return ResourceManager.GetString("Home_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName_Label {
            get {
                return ResourceManager.GetString("LastName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading….
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with your email.
        /// </summary>
        public static string Login_Instruction {
            get {
                return ResourceManager.GetString("Login_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login — The Vape Shop Sarnia.
        /// </summary>
        public static string Login_PageTitle {
            get {
                return ResourceManager.GetString("Login_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Nav_Account {
            get {
                return ResourceManager.GetString("Nav_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Panel.
        /// </summary>
        public static string Nav_AdminPanel {
            get {
                return ResourceManager.GetString("Nav_AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        public static string Nav_Brands {
            get {
                return ResourceManager.GetString("Nav_Brands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Nav_Cart {
            get {
                return ResourceManager.GetString("Nav_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Nav_Categories {
            get {
                return ResourceManager.GetString("Nav_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Nav_Dashboard {
            get {
                return ResourceManager.GetString("Nav_Dashboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deals.
        /// </summary>
        public static string Nav_Deals {
            get {
                return ResourceManager.GetString("Nav_Deals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Nav_Products {
            get {
                return ResourceManager.GetString("Nav_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Nav_Search {
            get {
                return ResourceManager.GetString("Nav_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Home.
        /// </summary>
        public static string NotFound_GoHome {
            get {
                return ResourceManager.GetString("NotFound_GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 — Page Not Found.
        /// </summary>
        public static string NotFound_Heading {
            get {
                return ResourceManager.GetString("NotFound_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the page you are looking for does not exist..
        /// </summary>
        public static string NotFound_Message {
            get {
                return ResourceManager.GetString("NotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found — The Vape Shop Sarnia.
        /// </summary>
        public static string NotFound_PageTitle {
            get {
                return ResourceManager.GetString("NotFound_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been placed successfully!.
        /// </summary>
        public static string OrderPlaced {
            get {
                return ResourceManager.GetString("OrderPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit {0} of {1}.
        /// </summary>
        public static string OtpInput_DigitAriaLabel {
            get {
                return ResourceManager.GetString("OtpInput_DigitAriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 8 characters..
        /// </summary>
        public static string Password_Hint {
            get {
                return ResourceManager.GetString("Password_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password_Label {
            get {
                return ResourceManager.GetString("Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters..
        /// </summary>
        public static string Password_TooShort {
            get {
                return ResourceManager.GetString("Password_TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo of {0}.
        /// </summary>
        public static string Product_ImageAlt {
            get {
                return ResourceManager.GetString("Product_ImageAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} left in stock.
        /// </summary>
        public static string Product_StockWarning {
            get {
                return ResourceManager.GetString("Product_StockWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Details — The Vape Shop Sarnia.
        /// </summary>
        public static string ProductDetail_PageTitle {
            get {
                return ResourceManager.GetString("ProductDetail_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product could not be found..
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products — The Vape Shop Sarnia.
        /// </summary>
        public static string Products_PageTitle {
            get {
                return ResourceManager.GetString("Products_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string SignIn_Heading {
            get {
                return ResourceManager.GetString("SignIn_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string SignIn_NoAccount {
            get {
                return ResourceManager.GetString("SignIn_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login — The Vape Shop Sarnia.
        /// </summary>
        public static string SignIn_PageTitle {
            get {
                return ResourceManager.GetString("SignIn_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back to The Vape Shop.
        /// </summary>
        public static string SignIn_WelcomeBack {
            get {
                return ResourceManager.GetString("SignIn_WelcomeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I confirm I am 19 years of age or older.
        /// </summary>
        public static string SignUp_AgeConfirm {
            get {
                return ResourceManager.GetString("SignUp_AgeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string SignUp_HaveAccount {
            get {
                return ResourceManager.GetString("SignUp_HaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string SignUp_Heading {
            get {
                return ResourceManager.GetString("SignUp_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join The Vape Shop — Canada&apos;s premium vaping destination.
        /// </summary>
        public static string SignUp_Instruction {
            get {
                return ResourceManager.GetString("SignUp_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create — The Vape Shop Sarnia.
        /// </summary>
        public static string SignUp_PageTitle {
            get {
                return ResourceManager.GetString("SignUp_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay tuned — We’ll be live soon.
        /// </summary>
        public static string Stay_Tuned {
            get {
                return ResourceManager.GetString("Stay_Tuned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 digits.
        /// </summary>
        public static string Verify_CodeHint {
            get {
                return ResourceManager.GetString("Verify_CodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the six-digit code sent to your email address.
        /// </summary>
        public static string Verify_CodeLabel {
            get {
                return ResourceManager.GetString("Verify_CodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Verify_Heading {
            get {
                return ResourceManager.GetString("Verify_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in as.
        /// </summary>
        public static string Verify_LoggedInAs {
            get {
                return ResourceManager.GetString("Verify_LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify — The Vape Shop Sarnia.
        /// </summary>
        public static string Verify_PageTitle {
            get {
                return ResourceManager.GetString("Verify_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend code.
        /// </summary>
        public static string Verify_Resend {
            get {
                return ResourceManager.GetString("Verify_Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend in {0}s.
        /// </summary>
        public static string Verify_ResendIn {
            get {
                return ResourceManager.GetString("Verify_ResendIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are signing up as.
        /// </summary>
        public static string Verify_SigningUpAs {
            get {
                return ResourceManager.GetString("Verify_SigningUpAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent a 6-digit code to {0}. Check your inbox (and spam folder)..
        /// </summary>
        public static string Verify_Subheading {
            get {
                return ResourceManager.GetString("Verify_Subheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Verify_Submit {
            get {
                return ResourceManager.GetString("Verify_Submit", resourceCulture);
            }
        }
    }
}
